{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1"}}

---
kind: ClusterRole
apiVersion: {{.Values.cr_api_version}}
metadata:
  name: {{ .Values.cr_name }}
  labels:
    component: {{ .Values.cr_component }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: {{ .Values.crb_api_version }}
metadata:
  name: {{ .Values.crb_name }}
  labels:
    component: {{ .Values.crb_component }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: {{ .Values.sa_name }}
  namespace: {{ .Values.sa_namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.cr_name }}
  apiGroup: ""

{{- end}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sa_name }}
  namespace: {{ .Values.sa_namespace }}
  labels:
    component: {{ .Values.sa_component }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas}}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      serviceAccountName: {{ .Values.sa_name }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image}}
        ports:
        - containerPort: {{ .Values.containerPort}}
      {{- if .Values.tolerations }}
      tolerations:
      {{- range .Values.tolerations }}
      - key: {{ .key | default ("") }}
        value: {{ .value | default ("")}}
        operator: {{ .operator | default ("Equal") }}
        effect: {{ .effect  | default ("")}}
      {{- end}}
      {{- end}}
      {{- if .Values.scheduling.affinity }}
      {{- if .Values.scheduling.affinity.node }}
      {{- if .Values.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
