---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: iptables-agent
  labels:
    name: iptables-agent
    release: {{.Release.Name | quote }}
    heritage: {{.Release.Service | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-iptables-agent"
    app: {{.Values.app}}
    version: {{.Chart.Version}}
spec:
  template:
    metadata:
      labels:
        app: {{.Values.app}}
        version: {{.Chart.Version}}
    spec:
      hostNetwork: true
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 65
      {{- if .Values.scheduling.affinity }}
      {{- if .Values.scheduling.affinity.node }}
      {{- if .Values.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
      {{- range .Values.tolerations }}
      - key: {{ .key | default ("") }}
        value: {{ .value | default ("")}}
        operator: {{ .operator | default ("Equal") }}
        effect: {{ .effect  | default ("")}}
      {{- end }}
      {{- end }}
