---
replicas: 1
color: E5CCFF
prometheus_image: "prom/prometheus:v1.2.1"
prometheus_port: 9090
prometheus_node_port: 30360
pushgateway_image: "prom/pushgateway:0.3.0"
pushgateway_port: 9091
pushgateway_node_port: 30362
config_dir: /etc/prometheus/
data_dir: /prometheus
storage_class: anything
# 1Gi is arbitrary here. See https://prometheus.io/docs/operating/storage/ for
# volume sizing information.
storage_size: 1Gi
tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
