backendImage: "gcr.io/google_containers/defaultbackend:1.0"
backend_tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
bodySize: "64m"
externalName:
hstsIncludeSubdomains: "false"
image: "gcr.io/google_containers/nginx-ingress-controller:0.8.3"
loadBalancerIP:
proxyConnectTimeout: "15"
proxyReadTimeout: "600"
proxySendTimeout: "600"
replicas: "1"
serverNameHashBucketSize: "256"
serviceType: "LoadBalancer"
tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
