backendImage: "gcr.io/google_containers/defaultbackend:1.0"
backend_tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
backend_scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
bodySize: "64m"
externalName:
hstsIncludeSubdomains: "false"
image: "gcr.io/google_containers/nginx-ingress-controller:0.8.3"
loadBalancerIP:
proxyConnectTimeout: "15"
proxyReadTimeout: "600"
proxySendTimeout: "600"
replicas: "1"
serverNameHashBucketSize: "256"
serviceType: "LoadBalancer"
nginx_tolerations:
 # - key: taintKey
 #   value: taintValue
 #   operator: Equal
 #   effect: NoSchedule
nginx_scheduling:
  affinity:
    node:
      type: #requiredDuringSchedulingIgnoredDuringExecution
      labels:
      # - key: iamalabelkey
      #   operator: In
      #   values: ["value1", "value2"]
