---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: podpincher
  name: podpincher
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: podpincher
  template:
    metadata:
      labels:
        cagby.io/color: {{.Values.color}}
        app: podpincher
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: Always
        name: podpincher
        env:
        - name: KUBERNETES_API_VER
          value: {{.Values.apiver}}
        - name: KUBERNETES_API_URL
          value: http://127.0.0.1:8001/api/
        ports:
        - containerPort: 4567
          hostPort: 4567
          protocol: TCP
      - image: "lachlanevenson/k8s-kubectl"
        name: kubectl
        args: [ "proxy", "--port=8001", "--accept-paths=^*$" ]
      {{- if .Values.tolerations }}
      tolerations:
      {{- range .Values.tolerations }}
      - key: {{ .key | default ("") }}
        value: {{ .value | default ("")}}
        operator: {{ .operator | default ("Equal") }}
        effect: {{ .effect  | default ("")}}
      {{- end }}
      {{- end }}
      {{- if .Values.scheduling.affinity }}
      {{- if .Values.scheduling.affinity.node }}
      {{- if .Values.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
